import {createEngine} from './engine.js?png=1';
const figure=document.querySelector('[data-image-demo]');
const control=name=>figure.querySelector(`[data-control="${name}"]`);
const view=name=>figure.querySelector(`[data-view="${name}"]`);
const kind=figure.dataset.imageDemo;
let blobUrl;
try{
 const engine=await createEngine();
 const render=()=>{
  if([...figure.querySelectorAll('input')].some(input=>!input.reportValidity()))return;
  const button=control('render');button.disabled=true;view('status').textContent='Drawing…';
  try{
   let result,description;
   if(kind==='mandelbrot'){
    const preset={whole:[-0.5,0,3],seahorse:[-0.745,0.186,0.04],bulb:[-1.25,0,0.5]}[control('view').value];
    result=engine.image(2,Number(control('iterations').value),300,200,Number(control('interlace').value),...preset);
    description=`${control('view').selectedOptions[0].text}, ${control('iterations').value} iterations; ${control('interlace').selectedOptions[0].text.toLowerCase()}. ${result.darkPixels} of 60,000 pixels are darker than mid-grey.`;
   }else if(kind==='topology'){
    const modulo=control('topology').value==='modulo',period=Number(control('period').value),rule=Number(control('rule').value);
    result=engine.image(modulo?1:0,rule,280,280,modulo?period:140);
    description=`Rule ${rule}, ${modulo?'modulo '+period:'integer-line'} movement, 280 generations.`;
    view('movement').textContent=modulo?'Left and right wrap; “stay” keeps its index, as in the article. The initial world contains just one black cell at 0.':'One black cell at 0; the window shows positions −140 through 139.';
    control('period').disabled=!modulo;
   }else{
    result=engine.image(0,Number(control('rule').value),150,150,Number(control('seed').value));
    description=`Rule ${control('rule').value}, initial cell ${control('seed').value}, 150 generations on the integer line.`;
   }
   const bytes=Uint8Array.from(result.pngHex.match(/../g),hex=>parseInt(hex,16));
   if(blobUrl)URL.revokeObjectURL(blobUrl);
   blobUrl=URL.createObjectURL(new Blob([bytes],{type:'image/png'}));
   view('image').src=blobUrl;view('image').alt=description;view('image').hidden=false;
   view('download').href=blobUrl;view('download').hidden=false;
   view('status').textContent=`${description} PNG: ${bytes.length.toLocaleString()} bytes, generated by Haskell.`;
   const chunks=[];const data=new DataView(bytes.buffer);
   for(let offset=8;offset<bytes.length;){const length=data.getUint32(offset);const tag=new TextDecoder().decode(bytes.slice(offset+4,offset+8));const crc=data.getUint32(offset+8+length);chunks.push(`${tag}: ${length.toLocaleString()} bytes · CRC ${crc.toString(16).padStart(8,'0')}`);offset+=length+12;}
   view('chunks').textContent=chunks.join(' · ');
   view('rows').textContent=kind==='mandelbrot'?`Region: ${control('view').selectedOptions[0].text}\nImage: ${result.width} × ${result.height}\nPixels darker than mid-grey: ${result.darkPixels}`:`First generation:\n${result.firstRow}\n\nLast generation:\n${result.lastRow}`;
  }catch(error){view('status').textContent='The figure could not be drawn. The original code remains below.';console.error(error);}
  finally{button.disabled=false;}
 };
 control('render').addEventListener('click',render);
 figure.querySelectorAll('select,input').forEach(input=>input.addEventListener('change',render));
 render();
}catch(error){view('status').textContent='The interactive figure could not load. The original code remains below.';console.error(error);}
addEventListener('pagehide',()=>{if(blobUrl)URL.revokeObjectURL(blobUrl);});
