import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {parseHTML} from 'linkedom';
const {document}=parseHTML(fs.readFileSync('dist/reader/index.html','utf8'));
const search=document.querySelector('#archive-search');
const kind=document.querySelector('#archive-kind');
// linkedom's select.value is read-only; the browser exposes a writable value.
Object.defineProperty(kind,'value',{value:'',writable:true});
const context=vm.createContext({document});
vm.runInContext(fs.readFileSync('dist/archive.js','utf8'),context);
const catalog=JSON.parse(fs.readFileSync('content/github-repositories.json'));
const repos=catalog.repositories.filter(repo=>!repo.fork || catalog.alwaysInclude.includes(repo.name));
const links=[...document.querySelectorAll('.archive-repositories a')];
assert.equal(links.length,repos.length);
assert.ok(!links.some(a=>a.textContent==='narya'),'Exclude clones of other people’s repositories');
for(const name of ['starkify','nightfall','bitcoin-verifier-wasm'])assert.ok(links.some(a=>a.textContent===name),'Keep Edward’s projects: '+name);
for(const repo of repos){
  const link=links.find(a=>a.getAttribute('href')===repo.html_url);
  assert.equal(link.textContent,repo.name);
  assert.equal(link.getAttribute('title'),repo.description||null,'GitHub description is the hover text');
  assert.equal(link.closest('ul').previousElementSibling.textContent,(repo.archiveDate||repo.created_at).slice(0,4),'Group by effective repository year');
}
function filter(query,type='') {search.value=query;kind.value=type;vm.runInContext('filter()',context);}
const visibleRepos=()=>links.filter(a=>!a.parentElement.hidden&&!a.closest('ul').hidden).map(a=>a.textContent);
const visibleYears=()=>[...document.querySelectorAll('.archive-year')].filter(h=>!h.hidden).map(h=>h.textContent);
filter('nominal sets');
assert.ok(visibleRepos().includes('name'),'Search matches description, not just name');
filter('nominal sets','Repository');
assert.deepEqual(visibleRepos(),['name']);
assert.deepEqual(visibleYears(),['2018']);
assert.equal(document.querySelector('#archive-count').textContent,'1 repository');
assert.equal(document.querySelector('#archive-empty').hidden,true);
assert.equal(document.querySelectorAll('.archive-entry:not([hidden])').length,0);
filter('haskell','Repository');
assert.ok(visibleRepos().includes('lens'),'Languages are searchable');
filter('2026','Repository');
assert.deepEqual(visibleYears(),['2026'],'Repository-only years are retained');
assert.equal(visibleRepos().length,repos.filter(r=>(r.archiveDate||r.created_at).startsWith('2026')).length);
assert.ok(visibleRepos().includes('thc'),'The new THC belongs to 2026');
filter('2015','Repository');
assert.ok(!visibleRepos().includes('thc'),'The reused repository date does not date the new THC');
filter('turbo haskell','Repository');
assert.ok(visibleRepos().includes('thc'),'THC is searchable by its current description');
filter('turbo haskell','Article');
const topicPath='reader/topics/turbo-haskell/';
const topic=parseHTML(fs.readFileSync('dist/'+topicPath+'index.html','utf8')).document;
assert.equal(topic.querySelector('h1').textContent,'Turbo Haskell');
const topicArticles=JSON.parse(fs.readFileSync('content/articles.json')).filter(a=>a.topics?.includes('Turbo Haskell')).sort((a,b)=>b.date.localeCompare(a.date));
assert.deepEqual([...topic.querySelectorAll('.package-section li a')].map(a=>new URL(a.getAttribute('href'),'https://comonad.com/'+topicPath).pathname),topicArticles.map(a=>'/'+a.path),'Topic lists its articles newest first');
for(const article of topicArticles){
  assert.ok([...document.querySelectorAll('.archive-entry:not([hidden]) h3')].some(h=>h.textContent===article.title),'Topic text is searchable');
  const page=parseHTML(fs.readFileSync('dist/'+article.path+'index.html','utf8')).document;
  const tag=page.querySelector('a[rel="tag"]');
  assert.equal(tag.textContent,'Turbo Haskell');
  for(const base of ['https://comonad.com/','https://ekmett.github.io/comonad.com/'])assert.equal(new URL(tag.getAttribute('href'),base+article.path).href,base+topicPath,'Topic links work under both hosting roots');
}
assert.ok(fs.readFileSync('dist/sitemap.xml','utf8').includes('/'+topicPath),'Topic is discoverable in the sitemap');
filter('lens','Article');
assert.equal(visibleRepos().length,0,'Content type filters remain independent');
assert.ok(document.querySelectorAll('.archive-entry:not([hidden])').length>0);
filter('kan extensions','Series');
assert.equal(document.querySelector('.chronological').hidden,true);
assert.ok([...document.querySelectorAll('.series-entry:not([hidden]) h3')].some(h=>h.textContent==='Kan Extensions'),'Series search still finds the collection');
assert.equal(visibleRepos().length,0);
filter('zz-no-such-repo');
assert.equal(document.querySelector('#archive-empty').hidden,false);
assert.deepEqual(visibleYears(),[]);
filter('');
assert.equal(visibleRepos().length,repos.length,'Clearing the search restores all repositories');
assert.equal(document.querySelectorAll('.archive-entry:not([hidden])').length,document.querySelectorAll('.archive-entry').length,'Clearing search restores all articles and recordings');
console.log(`Archive search passed: ${repos.length} repository descriptions, creation years, type filters, and no-match handling.`);
