import fs from 'node:fs';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {parseHTML} from 'linkedom';
import {portQuine} from '../tools/build-quine.mjs';
const read=path=>fs.readFileSync(path,'utf8');
const hash=path=>crypto.createHash('sha256').update(fs.readFileSync(path)).digest('hex');
const manifest=JSON.parse(read('content/assets/quine/provenance.json'));
for(const file of manifest.files){
  assert.equal(hash(file.archive),file.sha256,'Original Quine source is unchanged');
  assert.equal(hash(file.archive.replace('content/','dist/')),file.sha256,'Published original is identical');
}
for(const root of ['content','dist'])assert.equal(hash(`${root}/assets/quine/original/quine-source.zip`),manifest.archiveSHA256,'Complete repository archive is intact');
for(const name of ['dodecahedron','generators']){
  const original=read(`content/assets/quine/original/${name}.frag`);
  const browser=read(`dist/assets/quine/${name}.frag`);
  assert.equal(browser,portQuine(name,original),'Published shader is generated by the mechanical port');
  // Undo every documented adaptation: the remaining math must be byte-identical.
  let restored=browser.replace(/^#version 300 es\nprecision highp float;\nprecision highp int;\n[^\n]*\n/,original.match(/^.*\n/)[0]);
  restored=restored.replace(/^uniform ((?:vec[24]|float) \w+);/gm,(_,declaration)=>original.match(new RegExp('^uniform '+declaration+' = [^;]+;','m'))[0]);
  if(name==='generators'){
    restored=restored.replace('void main(void)\n{\n#ifdef ENABLE_VIBRATION\n    vibration=sin(iGlobalTime*60.)*.0013;\n#endif','void main(void)\n{');
    restored=restored.replace('#ifdef ENABLE_VIBRATION\nfloat vibration=0.;','#ifdef ENABLE_VIBRATION\nfloat vibration=sin(iGlobalTime*60.)*.0013;');
    restored=restored.replace(/\bproceduralTexture\(/g,'texture(');
    assert.match(browser,/@var license CC BY-NC-SA 3.0/);
  }
  assert.equal(restored,original,'No changes to ray marching, camera path, or shading');
}
const page=parseHTML(read('dist/reader/2014/quine-shader-toys/index.html')).document;
assert.ok(page.querySelector('.quine-demo canvas[tabindex="0"]'));
assert.equal(page.querySelector('.article-meta time').getAttribute('datetime'),manifest.firstShaderCommits.dodecahedron.date);
assert.ok(page.querySelector('script[src$="quine-demo.js"]'));
assert.ok(page.querySelector('a[href$="quine-source.zip"]'));
const archive=parseHTML(read('dist/reader/index.html')).document;
assert.ok(archive.querySelector('a[href$="reader/2014/quine-shader-toys/"]'),'Demo is interleaved with articles');
console.log('Quine passed: original sources, repository archive, unchanged shader algorithms, and dated archive entry.');
